"""Single registry of API error codes (ADR-0006, Decision 2).

Adding a code anywhere else in the codebase is prohibited.
"""

AUTH_MISSING_TOKEN = "AUTH_MISSING_TOKEN"  # nosec B105
AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN"  # nosec B105
TENANT_MISMATCH = "TENANT_MISMATCH"
VALIDATION_FAILED = "VALIDATION_FAILED"
NOT_FOUND = "NOT_FOUND"
METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
NOT_READY = "NOT_READY"
INTERNAL_ERROR = "INTERNAL_ERROR"
USER_PROFILE_NOT_FOUND = "USER_PROFILE_NOT_FOUND"
RATE_LIMITED = "RATE_LIMITED"
FORBIDDEN_ROLE = "FORBIDDEN_ROLE"
FACILITY_NOT_FOUND = "FACILITY_NOT_FOUND"
INVALID_DATE = "INVALID_DATE"
SLOT_NOT_BOOKABLE = "SLOT_NOT_BOOKABLE"
BOOKING_QUOTA_EXCEEDED = "BOOKING_QUOTA_EXCEEDED"
ALREADY_BOOKED = "ALREADY_BOOKED"
SLOT_CONTENDED = "SLOT_CONTENDED"
LOCK_UNAVAILABLE = "LOCK_UNAVAILABLE"

HTTP_ERROR_CODES = {
    404: NOT_FOUND,
    405: METHOD_NOT_ALLOWED,
}
